### ISSUE TITLE
Mounting Errors in Toolkit and Playground

### ISSUE THREAD

**Issue by 416e746f6e** [sensepost/routopsy#1]
Hello I am using:

Ubuntu20.04 (VM)
Docker version 19.03.8
docker-compose version 1.25.0
Python version 3.8.5

For Playground:

When using the provided .yml file the Build crashes due to a mounting Error. 
I could fix it by changing:

              volumes:
                  - ./frr_configs/daemons:/etc/frr/daemons
                  -  [...]

to:

              volumes:
                  - /absolute/path/frr_configs/daemons:/etc/frr/daemons
                  -  [...]

The Problem is with the Toolkit itself that the mounting of the config files fails for me when using the attack command.

> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/containers/394e21a95222d73c68a8b7268dae4a417d59b47d49e603d0f89a9e8a5a18ff21/start
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 384, in <module>
    main()
  File "main.py", line 188, in main
    docker_wrapper.build_and_run_container()
  File "/home/anton/routopsy/routopsy-toolkit/docker_wrapper.py", line 73, in build_and_run_container
    container = client.containers.run('frrouting/frr', name=docker_name, cap_add=\
  File "/usr/lib/python3/dist-packages/docker/models/containers.py", line 809, in run
    container.start()
  File "/usr/lib/python3/dist-packages/docker/models/containers.py", line 400, in start
    return self.client.api.start(self.id, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/tmp/config/daemons\\\" to rootfs \\\"/var/lib/docker/overlay2/55fe5be46f48ba8faaa5bd20ec3c0081f8b4a9eca2006d2d84b0617744e91b9c/merged\\\" at \\\"/var/lib/docker/overlay2/55fe5be46f48ba8faaa5bd20ec3c0081f8b4a9eca2006d2d84b0617744e91b9c/merged/etc/frr/daemons\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type")

The Error is basicaly the same I had with the compose files.
I assume the Issues is within the container creation. Sorry if this is something obvious im missing but I am new to Docker. Thanks!

**Comment by GOAT-FARM3R** [comment]
Hi, thanks for notifying us about the issue. We have pushed the fixes and its working our side. Let us know if its working your side too?

**Comment by 416e746f6e** [comment]
Yes the version-fix resolved the issue, thanks!
